# Generated by Django 5.1.1 on 2024-09-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0002_channelsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('path', models.URLField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('number_of_views', models.BigIntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='videos/images/')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='studio.channel')),
            ],
        ),
    ]
